/*
 *
 * NOTE: This file automatically generated by the Tecplot GUI Builder.
 *       Do not edit this file!
 *
 */


/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
    if (Dialog1Manager != BADDIALOGID)
        return;
    Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                                4383,
                                                2250,
                                                "test01 title",
                                                Dialog1Init_CB,
                                                Dialog1CloseButton_CB,
                                                Dialog1HelpButton_CB);
}


/**
 */
void InitTGB(void)
{
    Dialog1Manager = BADDIALOGID;
}
