/*
 *
 * NOTE: This file automatically generated by the Tecplot GUI Builder.
 *       Do not edit this file!
 *
 */
#include "TECADDON.h"
#include "GUIDEFS.h"

LgIndex_t  Dialog1Manager = BADDIALOGID;
