/*
 *
 * NOTE: This file automatically generated by the Tecplot GUI Builder.
 *       Do not edit this file!
 *
 */
extern void InitTGB(void);
extern LgIndex_t  Dialog1Manager;
extern void BuildDialog1(int  ParentDialog);
